myapp/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name='myapp'
urlpatterns = [
    path('', views.index),
    path('products/', views.products, name='products'),
    path('products/<int:pk>', views.ProductDetailView.as_view(), name='detailed_page'),
    path('products/add/', views.AddProduct.as_view(), name='add_product'),
    path('products/update/<int:pk>', views.UpdateProduct.as_view(), name='update_product'),
    path('products/delete/<int:pk>', views.DeleteProduct.as_view(), name='delete_product'),
    path('products/mylistings', views.my_listings, name='mylistings')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('users/', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name='users'
urlpatterns = [
    path('register/', views.registration, name='registration'),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('createprofile/', views.create_profile, name='create_profile'),
    path('sellerprofile/<int:id>', views.seller_profile, name='seller_profile'),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here. hello
class Product(models.Model):
    def __str__(self) -> str:
        return self.name
    
    def get_absolute_url(self):
        return reverse("myapp:products")
    
    
    seller_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length = 100)
    price = models.IntegerField()
    description = models.CharField(max_length = 200)
    image = models.ImageField(blank=True, upload_to="images")

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    def __str__(self):
        return self.user.username
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile.jpg', upload_to='profile_pics')
    contact_number = models.CharField(max_length=100, default='123456789')

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class':'focus:outline-none', 'placeholder':'demo@gmail.com'}))
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'focus:outline-none', 'placeholder':'User123'}))
    password1 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class':'focus:outline-none'}))
    password2 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class':'focus:outline-none'}))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


    ## need to look through
    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

myapp/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse
from . models import Product
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.core.paginator import Paginator

# Create your views here.

def index(request):
	return HttpResponse("Hello world")

# Function based 
def products(request):
	page_obj = products = Product.objects.all()

	product_name = request.GET.get('product_name')
	if product_name != '' and product_name is not None:
		page_obj = products.filter(name__icontains = product_name)
	paginator = Paginator(page_obj, 3)
	page_num = request.GET.get('page')
	page_obj = paginator.get_page(page_num)

	context = {
		'page_obj':page_obj
	}
	return render(request, 'myapp/index.html', context)

# Class based view
class ListOfProducts(ListView):
	model = Product
	template_name = 'myapp/index.html'
	context_object_name = 'products'
	paginate_by = 3



# function based
def detailed(request, id):
	product = Product.objects.get(id=id)

	context = {
		'product':product
	}
	return render(request, 'myapp/detail.html', context)

class ProductDetailView(DetailView):
	model = Product
	template_name = "myapp/detail.html"
	context_object_name = 'product'



# function based 
@login_required
def addprod(request):
	if request.method == 'POST':
		name = request.POST.get('name')
		price = request.POST.get('price')
		desc = request.POST.get('description')
		image = request.FILES['upload']
		seller_name = request.user

		product = Product(name=name, price=price, description=desc, image=image, seller_name=seller_name)
		product.save()

	return render(request, 'myapp/addproduct.html')


#class based
class AddProduct(CreateView):
	model = Product
	fields = ['name', 'price', 'description', 'image', 'seller_name']



#function based
def update_product(request, id):
	product = Product.objects.get(id=id)
	if request.method == 'POST':
		product.name = request.POST.get('name')
		product.price = request.POST.get('price')
		product.description = request.POST.get('description')
		print(request.FILES['upload'])
		if request.FILES['upload'] == '':
			product.image = request.FILES['upload']
		product.save()

		return redirect('/myapp/products')

	
	context = {
		'product':product
	}
	return render(request, 'myapp/updateproduct.html', context)


#class based
class UpdateProduct(UpdateView):
	model = Product
	fields = ['name', 'price', 'description', 'image', 'seller_name']
	template_name_suffix = '_update_form'


# funtion based
def delete_product(request, id):
	product = Product.objects.get(id=id)
	context = {
		'product':product,
	}
	if request.method == 'POST':
		product.delete()
		return  redirect('/myapp/products')
	
	return render(request, 'myapp/delete.html', context)
	

#class based
class DeleteProduct(DeleteView):
	model = Product
	success_url = reverse_lazy("myapp:products")



def my_listings(request):
	products = Product.objects.filter(seller_name = request.user)

	context = {
		"products":products,
	}

	return render(request, 'myapp/mylistings.html', context=context)

users/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.contrib.auth.decorators import login_required
from . models import Profile
from django.contrib.auth.models import User
# Create your views here.

def registration(request):
    print(request.method)
    
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        print(form.errors)
        if form.is_valid():
            user = form.save()
            return redirect('myapp/products')
        else:
            errors = form.errors
            conte = {
                'errors':errors,
            }
            return render(request, 'users/register.html', context=conte)
            

    form = NewUserForm()
    context = {
        'form':form,
    }
    return render(request, 'users/register.html', context)

@login_required
def profile(request):
    return render(request, 'users/profile.html')

def create_profile(request):
    if request.method == "POST":
        contact_number = request.POST.get('contact_number')
        image = request.FILES['upload']
        user = request.user
        profile = Profile(user = user, image = image, contact_number = contact_number)
        profile.save()
    return render(request, 'users/createprofile.html')


def seller_profile(request, id):
    seller = User.objects.get(id=id)

    context={
        'seller':seller,
    }
    return render(request, 'users/sellerprofile.html', context)

myapp/templates/myapp/addproduct.html
{%extends 'myapp/base.html'%}
{%block content%}
<form class="bg-white shadow-md py-8 w-3/5 m-10 px-10" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h1 class="text-2xl font-bold m-10">Add Product page</h1>
    <div class="mb-5">
        <label class="block text-gray-700 text-sm font-bold mb-3" for="">Product name</label>
        <input class="shadow appearence-none border rounded py-2 px-3 mr-10 text-gray -700" placeholder="Name" type="text" name="name" id="name">
    </div>
    <div class="mb-5">
        <label class="block text-gray-700 text-sm font-bold mb-3" for="">Product price</label>
        <input class="shadow appearence-none border rounded py-2 px-3 mr-10 text-gray -700" placeholder="Price" type="text" name="price" id="price">
    </div>
    <div class="mb-5">
        <label class="block text-gray-700 text-sm font-bold mb-3" for="">Product description</label>
        <input  class="shadow appearence-none border rounded py-2 px-3 mr-10 text-gray -700" placeholder="Description" type="text" name="description" id="description">
    </div>
    <div class="mb-5">
        <label class="block text-gray-700 text-sm font-bold mb-3" for="">Product image</label>
        <input class="py-2" type="file" accept="image/*" name="upload" id="upload">
    </div>
    <div class="mb-5">
        <input class="bg-green-500 text-white px-5 py-2" type="submit" name="Add product" value="Add Product" id="">
    </div>
    
</form>
{%endblock%}

myapp/templates/myapp/base.html
{%load static%}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'myapp/styles.css' %}"
    </head>
    <body>
        <nav class="bg-white shadow-lg">
            <div class="max-w-6xl mx-auto px-4">
                <div class="flex justify-between">
                    <div class="flex space-x-7">
                        <div>
                            <a href="{%url 'myapp:products'%}" class="flex px-2 py-4 items-center">
                                <img class="h-9 w-9" src="{% static 'myapp/images/logo.png'%}", alt="There is an logo">
                                <span class="text-gray-500 font-semibold text-lg">Buy&SEll</span>
                            </a>
                        </div>
                        <div class="items-center space-x-1 flex">
                            <a href="" class="py-4 px-2 text-gray-500 font-semibold border-green-500 border-b-2">Home</a>
                            <a href="{%url 'myapp:products'%}" class="py-4 px-2 text-gray-500 font-semibold">View Products</a>
                            <a href="{%url 'myapp:add_product'%}" class="py-4 px-2 text-gray-500 font-semibold">Post and Add</a>
                            <div class="pl-50">
                                {%if user.is_authenticated %}
                                    <a class="py-4 px-4 text-gray-500 font-semibold" href='{% url 'users:logout' %}'>Log out</a>
                                    <a class="py-4  text-gray-500 font-semibold" href='{% url 'users:profile' %}'>Profile</a>
                                    <a class=" px-5 text-gray-500 font-semibold" href='{% url 'myapp:mylistings' %}'>My listings</a>
                                {%else%}
                                    <a class = "py-4 px-10 text-gray-500 font-semibold" href='{% url 'users:login'%}'>Login</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
        {% block content %}

        {% endblock %}
    </body>
</html>

myapp/templates/myapp/delete.html
{%extends 'myapp/base.html'%}
{%block content%}
<h1 class="text-2xl m-10 font-bold">Delete Product</h1>

<form method="POST" class="bg-white shadow-md m-10 w-3/5 rounded px-8 pb-8 pt-6 mb-4">
    {%csrf_token%}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm mb-2 font-bold">Are you sure want to delete</label>
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm mb-2 font-bold"> {{product.name}} </label>
    </div>
    <div class="mb-4">
        <img src="{{product.image.url}}">
    </div>
    <input class="bg-red-500 text-white px-5 py-2" type=submit name="confirm" id="confirm" value="Confirm">
    <a class="button bg-green-500 text-white px-5 py-2.5 ml-4" href="{% url 'myapp:products'%}">Cancel</a>
</form>
{%endblock%}

myapp/templates/myapp/detail.html
{%extends 'myapp/base.html' %}
{%block content%}

<div class="flex p-10 w-full h-200">
    <img class="w-1/3" src="{{product.image.url}}">
    <div class="w-2/3 text-xl ml-7">
        <div class="mt-5">{{product.name}}</div>
        <div class="mt-5 text-green-700"> ${{product.price}}</div>
        <div class="mt-5">{{product.description}}</div>
        <div class="mt-5">Posted by:<a href="{% url 'users:seller_profile' product.seller_name.id%}">{{product.seller_name.username}}</a></div>
        <div class="mt-5">Conatct number:{{product.seller_name.profile.contact_number}}</div>
    </div>
</div>

{%endblock%}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% load static %}
{%block content%}
    <main>
        <div class="mt-10 px-4 max-w-7xl mx-auto sm:st-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
            <h1 class="text-4xl text-gray-900 font-bold sm:text-5xl md:text-6xl">
                <span class="block xl:inline">Premium products</span>
                <span class="block text-green-500 xl:inline">Non-premium products</span>
            </h1>
            <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Get the best used products accross the globe. Free shipping </p>
        </div>
    </main>

    <div class="flex p-10 justify-center">
        <h2 class="text-3xl font-normal mt-0 mb-2 text-gray-500">Recent Products</h2>
    </div>
    <div class="mt-5 p-10 justify-center">
        <h2>Search products</h2>
        <form method="GET">
            <input type=text name="product_name" id="product_name" placeholder="product to search" class="font-bold text-gray-700 text-lg">
        </form>
    </div>

    <div class = "p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-cols-3 lg:grid-cols-3 gap-5">
        <!--   Card Layout   -->
        {% for product in page_obj%}
        <a href="{% url 'myapp:detailed_page' product.id%}">
            <div class="rounded overflow-hidden shadow-lg">
                <img class="w-full" src="{{product.image.url}}">
                <div class="px-6 py-6">
                    <div class="font-bold text-xl mb-2">{{product.name}}</div>
                    <div class="font-bold text-xl text-green-500 mb-2"> ${{product.price}}</div>
                    <div class="font-bold mb-2"> Posted by:<span class="text-indigo-500">{{product.seller_name}}</span></div>
                    <p class="text-base text-gray-500">{{product.description}}</p>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
    <div class="pagination justify-center flex mb-20">
        <span>
            {%if page_obj.has_previous %}
            <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z-10" href="?page=1">First</a>
            <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z-10" href="?page={{page_obj.previuos_page_number}}">Previous</a>
            {%endif%}
            <span class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z-10">
                Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
            </span>
            {%if page_obj.has_next%}
                <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z-10" href="?page={{page_obj.next_page_number}}">Next</a>
                <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z-10" href="?page={{page_obj.paginator.num_pages}}">Last</a>
            {%endif%}
            
        </span>
    </div>
    


{%endblock%}

myapp/templates/myapp/mylistings.html
{%extends 'myapp/base.html'%}
{%block content%}
<div class="m-10 p-10 text-2xl font-bold">
    My lsitings
</div>
{% for product in products%}
    <div class="itemcontainer flex shadow-lg m-10 p-10">
        <span class="w-1/5">
            <img src="{{product.image.url}}" class="w-40 h-40">
        </span>
        <span class="w-3/5">
            <div class="font-bold text-gray-700"> {{product.name}} </div>
            <div class="text-green-500">$ {{product.price}} </div>
            <div> {{product.description}} </div>
        </span>
        <span class="w-1/5 m-10">
            <a href="{%url 'myapp:update_product' product.id %}"class="font-bold px-5 py-2 text-white bg-green-500">Edit</a> 
        </span>
        <span class="w-1/5 m-10">
            <a href="{%url 'myapp:delete_product' product.id%}" class="font-bold px-5 py-2 text-white bg-red-500">Delete</a> 
        </span>
    </div>
{% endfor%}
{%endblock%}

myapp/templates/myapp/product_confirm_delete.html
<form method="POST">
    {%csrf_token%}
    <p> Are u sure want to delete {{object}} </p>
    {{form}}
    <input type="submit" value="Confirm">
</form>

myapp/templates/myapp/product_form.html
{%extends 'myapp/base.html'%}
{%block content%}
<form class="bg-white shadow-md py-8 w-3/5 m-10 px-10" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h1 class="text-2xl font-bold m-10">Add Product page</h1>
    <div class="mb-5">
        <label class="block text-gray-700 text-sm font-bold mb-3" for="">Product name</label>
        <div class="shadow appearence-none border rounded py-2 px-3 mr-10 text-gray -700 w-2/5">
            {{form.name}}
        </div>
    </div>
    <div class="mb-5">
        <label class="block text-gray-700 text-sm font-bold mb-3" for="">Product price</label>
        <div class="shadow appearence-none border rounded py-2 px-3 mr-10 text-gray -700 w-2/5">
            {{form.price}}
        </div>
    </div>
    <div class="mb-5">
        <label class="block text-gray-700 text-sm font-bold mb-3" for="">Product description</label>
        <div class="shadow appearence-none border rounded py-2 px-3 mr-10 text-gray -700 w-2/5">
            {{form.description}}
        </div>
    </div>
    <div class="mb-5">
        <label class="block text-gray-700 text-sm font-bold mb-3" for="">Product image</label>
        <div class="shadow appearence-none border rounded py-2 px-3 mr-10 text-gray -700 w-2/5">
            {{form.image}}
        </div>
    </div>
    <div class="shadow hidden appearence-none border rounded py-2 px-3 mr-10 text-gray -700 w-1/4">
        {{form.seller_name}}
    </div>
    <div class="mb-5">
        <input class="bg-green-500 text-white px-5 py-2" type="submit" name="Add product" value="Add Product" id="">
    </div>
</form>
{%endblock%}

myapp/templates/myapp/product_update_form.html
<form method="POST" enctype="multipart/form">
    {% csrf_token%}
    {{form.as_p}}
    <input type="submit" value="Update">
</form>

myapp/templates/myapp/updateproduct.html
{%extends 'myapp/base.html'%}
{%block content%}
<form class="bg-white shadow-md py-8 w-3/5 m-10 px-10" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h1 class="text-2xl font-bold m-10">Update Product page</h1>
    <div class="mb-5">
        <label class="block text-gray-700 text-sm font-bold mb-3" for="">Product name</label>
        <input class="shadow appearence-none border rounded py-2 px-3 mr-10 text-gray -700" placeholder="Name" type="text" name="name" id="name" value="{{product.name}}">
    </div>
    <div class="mb-5">
        <label class="block text-gray-700 text-sm font-bold mb-3" for="">Product price</label>
        <input class="shadow appearence-none border rounded py-2 px-3 mr-10 text-gray -700" placeholder="Price" type="text" name="price" id="price" value = "{{product.price}}">
    </div>
    <div class="mb-5">
        <label class="block text-gray-700 text-sm font-bold mb-3" for="">Product description</label>
        <input  class="shadow appearence-none border rounded py-2 px-3 mr-10 text-gray -700" placeholder="Description" type="text" name="description" id="description" value="{{product.description}}">
    </div>
    <div class="mb-5">
        <img class="w-20 h-20" src = "{{product.image.url}}">
        <label class="block text-gray-700 text-sm font-bold mb-3" for="">Product image</label>
        <input class="py-2" type="file" accept="image/*" name="upload" id="upload" required>
    </div>
    <div class="mb-5">
        <input class="bg-green-500 text-white px-5 py-2" type="submit" name="Add product" value="Update Product" id="">
    </div>
    
</form>
{%endblock%}

users/templates/users/createprofile.html
{% extends 'myapp/base.html'%}
{% block content%}
<form enctype="multipart/form-data" method="POST" class="bg-whit shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-6 mb-4">
    {% csrf_token%}
    <div class="mb-4">
        <label for="">Upload profile image</label>
        <input class="py-2"placeholder="upload a profile pic" type="file" accept="image/*" name="upload" id="upload">
    </div>
    <div class="mb-4">
        <label for="contact_number">Contact_number</label>
        <input class="shadow appearence-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="123456789" type="text" accept="image/*" name="contact_number" id="contact_number">
    </div>
    <input class="bg-green-500 px-5 py-2 text-white" name="add" id="add" value="Add" type=submit>
</form>
{%endblock%}

users/templates/users/login.html
{%extends 'myapp/base.html'%}
{%block content%}
<h1 class="font-bold text-2xl m-10">Login user</h1>
<div class="container py-5">
    <form method="POST" class="w-2/5 bg-white shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}
        <div class="mb-2">
            <label class="block text-sm font-bold mb-2 text-gray-700" for=""> Username </label>
            <div class="py-2 px-3 mr-10 text-gray-700 leading-tight shadow appearence-none border rounded">
                {{form.username}}
            </div>
        </div>

        
        <div class="mb-2">
            <label class="block text-sm font-bold mb-2 text-gray-700" for=""> Password </label>
            <div class="py-2 px-3 mr-10 text-gray-700 leading-tight shadow appearence-none border rounded">
                {{form.password}}
            </div>
        </div>
        
        <button class="bg-green-500 text-white px-5 py-2 mt-5" type="submit">Login</button>
    </form>
    <div class="m-10"> Don't have an account ? <a href="{%url 'users:registration'%}" class="text-indigo-500">Register</a></div>
    
</div>

{{errors}}

{%endblock%}

users/templates/users/logout.html
{% extends 'myapp/base.html'%}
{%block content%}
<h1> You have been logged out successfully</h1>
{%endblock%}

users/templates/users/profile.html
{% extends 'myapp/base.html' %}
{%block content %}
<div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
    <div class="rounded shadow-lg">
        <div class="mx-auto">
            <img src="{{user.profile.image.url}}" alt="">
        </div>
        <div class="text-xl font-bold mb-2 px-6 py-4">
            {{user.username}}
        </div>
        <div class="text-xl font-bold mb-2 px-6 py-4">
            {{user.profile.contact_number}}
        </div>
    </div>
</div>
{%endblock%}

users/templates/users/register.html
{%extends 'myapp/base.html'%}
{%block content%}
<h1 class="font-bold text-2xl m-10">Register User</h1>
<div class="container py-5">
    <form method="POST" class="w-2/5 bg-white shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}
        <div class="mb-2">
            <label class="block text-sm font-bold mb-2 text-gray-700" for=""> Username </label>
            <div class="py-2 px-3 mr-10 text-gray-700 leading-tight shadow appearence-none border rounded">
                {{form.username}}
            </div>
        </div>

        <div class="mb-2">
            <label class="block text-sm font-bold mb-2 text-gray-700" for=""> Email </label>
            <div class="py-2 px-3 mr-10 text-gray-700 leading-tight shadow appearence-none border rounded">
                {{form.email}}
            </div>
        </div>
        <div class="mb-2">
            <label class="block text-sm font-bold mb-2 text-gray-700" for=""> Password </label>
            <div class="py-2 px-3 mr-10 text-gray-700 leading-tight shadow appearence-none border rounded">
                {{form.password1}}
            </div>
        </div>
        <div class="mb-2">
            <label class="block text-sm font-bold mb-2 text-gray-700" for=""> Confirm Password </label>
            <div class="py-2 px-3 mr-10 text-gray-700 leading-tight shadow appearence-none border rounded">
                {{form.password2}}
            </div>
        </div>
        <button class="bg-green-500 text-white px-5 py-2 mt-5" type="submit">Register</button>
    </form>
    <div class="m-10"> Already have an account ? <a href="{%url 'users:login'%}" class="text-indigo-500">Login</a></div>
</div>

{{errors}}

{%endblock%}

users/templates/users/sellerprofile.html
{% extends 'myapp/base.html'%}
{% block content%}
    <div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
        <div class="rounded shadow-lg">
            <div class="mx-auto">
                <img src="{{seller.profile.image.url}}" alt="">
            </div>
            <div class="text-xl font-bold mb-2 px-6 py-4">
                {{seller.username}}
            </div>
            <div class="text-xl font-bold mb-2 px-6 py-4">
                {{seller.profile.contact_number}}
            </div>
        </div>
    </div>
{% endblock %}